"""
Add these 85 growth stocks to src/config/tickers.py TIER_2_STOCKS list.

Copy the TickerMetadata entries below and paste them into the TIER_2_STOCKS list
in src/config/tickers.py (after the existing TIER_2_STOCKS entries).
"""

ADDITIONS = [
    # ========== AI & TECHNOLOGY - CHIPS (8) ==========
    TickerMetadata(
        symbol="MSFT",
        name="Microsoft Corporation",
        category="sector",
        sub_category="technology",
        weight=1.0,
        description="AI + Cloud leader - Azure, OpenAI partnership, enterprise dominance",
    ),
    TickerMetadata(
        symbol="AVGO",
        name="Broadcom Inc.",
        category="sector",
        sub_category="technology",
        weight=0.95,
        description="Networking chips - data center infrastructure, AI networking",
    ),
    TickerMetadata(
        symbol="QCOM",
        name="Qualcomm Inc.",
        category="sector",
        sub_category="technology",
        weight=0.9,
        description="Mobile AI chips - smartphone 5G/AI, automotive chips",
    ),
    TickerMetadata(
        symbol="MRVL",
        name="Marvell Technology Inc.",
        category="sector",
        sub_category="technology",
        weight=0.85,
        description="Data center chips - AI infrastructure, cloud networking",
    ),
    TickerMetadata(
        symbol="ARM",
        name="ARM Holdings PLC",
        category="sector",
        sub_category="technology",
        weight=0.9,
        description="Chip architecture - powers most smartphones, AI edge devices",
    ),
    TickerMetadata(
        symbol="ASML",
        name="ASML Holding NV",
        category="sector",
        sub_category="technology",
        weight=0.95,
        description="Chip manufacturing equipment - monopoly on EUV lithography",
    ),
    TickerMetadata(
        symbol="AMAT",
        name="Applied Materials Inc.",
        category="sector",
        sub_category="technology",
        weight=0.85,
        description="Chip equipment - semiconductor manufacturing tools",
    ),
    TickerMetadata(
        symbol="LRCX",
        name="Lam Research Corporation",
        category="sector",
        sub_category="technology",
        weight=0.85,
        description="Chip equipment - wafer fabrication equipment",
    ),
    TickerMetadata(
        symbol="KLAC",
        name="KLA Corporation",
        category="sector",
        sub_category="technology",
        weight=0.8,
        description="Chip inspection - process control for chip manufacturing",
    ),

    # ========== AI & TECHNOLOGY - SOFTWARE (7) ==========
    TickerMetadata(
        symbol="META",
        name="Meta Platforms Inc.",
        category="sector",
        sub_category="technology",
        weight=0.95,
        description="AI + Social - Facebook, Instagram, AI research, VR/AR",
    ),
    TickerMetadata(
        symbol="CRM",
        name="Salesforce Inc.",
        category="sector",
        sub_category="technology",
        weight=0.9,
        description="Enterprise AI - CRM platform with AI integration",
    ),
    TickerMetadata(
        symbol="NOW",
        name="ServiceNow Inc.",
        category="sector",
        sub_category="technology",
        weight=0.9,
        description="Enterprise automation - IT service management with AI",
    ),
    TickerMetadata(
        symbol="SNOW",
        name="Snowflake Inc.",
        category="sector",
        sub_category="technology",
        weight=0.85,
        description="Data cloud - data warehousing, AI data platform",
    ),
    TickerMetadata(
        symbol="PLTR",
        name="Palantir Technologies Inc.",
        category="sector",
        sub_category="technology",
        weight=0.85,
        description="AI analytics - government/enterprise data analytics",
    ),
    TickerMetadata(
        symbol="NET",
        name="Cloudflare Inc.",
        category="sector",
        sub_category="technology",
        weight=0.8,
        description="Edge computing - CDN, security, serverless at edge",
    ),

    # ========== CLEAN ENERGY & EVs (12) ==========
    TickerMetadata(
        symbol="RIVN",
        name="Rivian Automotive Inc.",
        category="sector",
        sub_category="automotive",
        weight=0.75,
        description="EV trucks - electric pickup trucks, Amazon partnership",
    ),
    TickerMetadata(
        symbol="LCID",
        name="Lucid Group Inc.",
        category="sector",
        sub_category="automotive",
        weight=0.7,
        description="Luxury EVs - premium electric sedans, battery technology",
    ),
    TickerMetadata(
        symbol="NIO",
        name="NIO Inc.",
        category="sector",
        sub_category="automotive",
        weight=0.75,
        description="Chinese EV leader - premium EVs, battery swap technology",
    ),
    TickerMetadata(
        symbol="LI",
        name="Li Auto Inc.",
        category="sector",
        sub_category="automotive",
        weight=0.7,
        description="Chinese EV - extended-range electric SUVs",
    ),
    TickerMetadata(
        symbol="XPEV",
        name="XPeng Inc.",
        category="sector",
        sub_category="automotive",
        weight=0.7,
        description="Chinese EV - autonomous driving, electric vehicles",
    ),
    TickerMetadata(
        symbol="ENPH",
        name="Enphase Energy Inc.",
        category="sector",
        sub_category="clean_energy",
        weight=0.85,
        description="Solar microinverters - residential solar leader",
    ),
    TickerMetadata(
        symbol="SEDG",
        name="SolarEdge Technologies Inc.",
        category="sector",
        sub_category="clean_energy",
        weight=0.8,
        description="Solar inverters - solar power optimization",
    ),
    TickerMetadata(
        symbol="RUN",
        name="Sunrun Inc.",
        category="sector",
        sub_category="clean_energy",
        weight=0.75,
        description="Residential solar - rooftop solar installation",
    ),
    TickerMetadata(
        symbol="FSLR",
        name="First Solar Inc.",
        category="sector",
        sub_category="clean_energy",
        weight=0.8,
        description="Solar panels - utility-scale solar manufacturing",
    ),
    TickerMetadata(
        symbol="ALB",
        name="Albemarle Corporation",
        category="sector",
        sub_category="materials",
        weight=0.85,
        description="Lithium - EV battery materials, lithium mining",
    ),
    TickerMetadata(
        symbol="SQM",
        name="Sociedad Quimica y Minera",
        category="sector",
        sub_category="materials",
        weight=0.75,
        description="Lithium - Chilean lithium producer for batteries",
    ),
    TickerMetadata(
        symbol="PLUG",
        name="Plug Power Inc.",
        category="sector",
        sub_category="clean_energy",
        weight=0.7,
        description="Hydrogen fuel cells - green hydrogen solutions",
    ),

    # ========== HEALTHCARE & BIOTECH (14) ==========
    TickerMetadata(
        symbol="LLY",
        name="Eli Lilly and Company",
        category="sector",
        sub_category="healthcare",
        weight=0.95,
        description="Obesity drugs - Mounjaro/Zepbound, diabetes, Alzheimer's",
    ),
    TickerMetadata(
        symbol="NVO",
        name="Novo Nordisk A/S",
        category="sector",
        sub_category="healthcare",
        weight=0.95,
        description="Obesity drugs - Ozempic/Wegovy leader, diabetes care",
    ),
    TickerMetadata(
        symbol="JNJ",
        name="Johnson & Johnson",
        category="sector",
        sub_category="healthcare",
        weight=0.9,
        description="Healthcare conglomerate - pharmaceuticals, medical devices",
    ),
    TickerMetadata(
        symbol="ABBV",
        name="AbbVie Inc.",
        category="sector",
        sub_category="healthcare",
        weight=0.85,
        description="Immunology - Humira successor drugs, oncology",
    ),
    TickerMetadata(
        symbol="GILD",
        name="Gilead Sciences Inc.",
        category="sector",
        sub_category="healthcare",
        weight=0.8,
        description="HIV/cancer - antiviral drugs, oncology",
    ),
    TickerMetadata(
        symbol="REGN",
        name="Regeneron Pharmaceuticals Inc.",
        category="sector",
        sub_category="healthcare",
        weight=0.85,
        description="Antibodies - monoclonal antibody therapies",
    ),
    TickerMetadata(
        symbol="VRTX",
        name="Vertex Pharmaceuticals Inc.",
        category="sector",
        sub_category="healthcare",
        weight=0.85,
        description="Gene therapy - cystic fibrosis, genetic diseases",
    ),
    TickerMetadata(
        symbol="MRNA",
        name="Moderna Inc.",
        category="sector",
        sub_category="healthcare",
        weight=0.75,
        description="mRNA vaccines - COVID vaccines, mRNA cancer treatments",
    ),
    TickerMetadata(
        symbol="BNTX",
        name="BioNTech SE",
        category="sector",
        sub_category="healthcare",
        weight=0.75,
        description="mRNA - Pfizer COVID vaccine partner, mRNA research",
    ),
    TickerMetadata(
        symbol="ISRG",
        name="Intuitive Surgical Inc.",
        category="sector",
        sub_category="healthcare",
        weight=0.9,
        description="Robotic surgery - da Vinci surgical systems monopoly",
    ),
    TickerMetadata(
        symbol="EW",
        name="Edwards Lifesciences Corporation",
        category="sector",
        sub_category="healthcare",
        weight=0.85,
        description="Heart valves - transcatheter heart valve leader",
    ),
    TickerMetadata(
        symbol="SYK",
        name="Stryker Corporation",
        category="sector",
        sub_category="healthcare",
        weight=0.85,
        description="Orthopedics - medical devices, joint replacements",
    ),
    TickerMetadata(
        symbol="BSX",
        name="Boston Scientific Corporation",
        category="sector",
        sub_category="healthcare",
        weight=0.8,
        description="Medical devices - cardiovascular, interventional",
    ),
    TickerMetadata(
        symbol="MDT",
        name="Medtronic PLC",
        category="sector",
        sub_category="healthcare",
        weight=0.85,
        description="Medical technology - pacemakers, diabetes devices",
    ),

    # ========== FINTECH & PAYMENTS (9) ==========
    TickerMetadata(
        symbol="V",
        name="Visa Inc.",
        category="sector",
        sub_category="financial",
        weight=0.95,
        description="Payment networks - global payments monopoly duopoly",
    ),
    TickerMetadata(
        symbol="MA",
        name="Mastercard Inc.",
        category="sector",
        sub_category="financial",
        weight=0.95,
        description="Payment networks - global payments monopoly duopoly",
    ),
    TickerMetadata(
        symbol="PYPL",
        name="PayPal Holdings Inc.",
        category="sector",
        sub_category="financial",
        weight=0.8,
        description="Digital payments - Venmo, online checkout",
    ),
    TickerMetadata(
        symbol="SQ",
        name="Block Inc.",
        category="sector",
        sub_category="financial",
        weight=0.75,
        description="Merchant payments - Square, Cash App, Bitcoin",
    ),
    TickerMetadata(
        symbol="ADYEN",
        name="Adyen NV",
        category="sector",
        sub_category="financial",
        weight=0.8,
        description="Payment processing - European payment platform",
    ),
    TickerMetadata(
        symbol="HOOD",
        name="Robinhood Markets Inc.",
        category="sector",
        sub_category="financial",
        weight=0.7,
        description="Commission-free trading - retail investor platform",
    ),
    TickerMetadata(
        symbol="SOFI",
        name="SoFi Technologies Inc.",
        category="sector",
        sub_category="financial",
        weight=0.7,
        description="Digital banking - student loans, financial services",
    ),
    TickerMetadata(
        symbol="AFRM",
        name="Affirm Holdings Inc.",
        category="sector",
        sub_category="financial",
        weight=0.7,
        description="Buy now pay later - installment payments",
    ),
    TickerMetadata(
        symbol="NU",
        name="Nu Holdings Ltd.",
        category="sector",
        sub_category="financial",
        weight=0.75,
        description="Brazilian digital bank - Latin American fintech",
    ),

    # ========== E-COMMERCE & CONSUMER (9) ==========
    TickerMetadata(
        symbol="AMZN",
        name="Amazon.com Inc.",
        category="sector",
        sub_category="consumer",
        weight=1.0,
        description="E-commerce + AWS - retail dominance, cloud leader",
    ),
    TickerMetadata(
        symbol="SHOP",
        name="Shopify Inc.",
        category="sector",
        sub_category="technology",
        weight=0.85,
        description="E-commerce platform - merchant tools, online stores",
    ),
    TickerMetadata(
        symbol="MELI",
        name="MercadoLibre Inc.",
        category="sector",
        sub_category="consumer",
        weight=0.8,
        description="Latin American e-commerce - Amazon of Latin America",
    ),
    TickerMetadata(
        symbol="SE",
        name="Sea Limited",
        category="sector",
        sub_category="technology",
        weight=0.75,
        description="Southeast Asian e-commerce - Shopee, gaming, fintech",
    ),
    TickerMetadata(
        symbol="NKE",
        name="Nike Inc.",
        category="sector",
        sub_category="consumer",
        weight=0.85,
        description="Athletic apparel - global brand, direct-to-consumer",
    ),
    TickerMetadata(
        symbol="LULU",
        name="Lululemon Athletica Inc.",
        category="sector",
        sub_category="consumer",
        weight=0.8,
        description="Athletic apparel - premium yoga/athleisure",
    ),
    TickerMetadata(
        symbol="SBUX",
        name="Starbucks Corporation",
        category="sector",
        sub_category="consumer",
        weight=0.8,
        description="Coffee - global coffeehouse chain",
    ),
    TickerMetadata(
        symbol="MCD",
        name="McDonald's Corporation",
        category="sector",
        sub_category="consumer",
        weight=0.85,
        description="Fast food - global fast food leader, real estate",
    ),
    TickerMetadata(
        symbol="CMG",
        name="Chipotle Mexican Grill Inc.",
        category="sector",
        sub_category="consumer",
        weight=0.8,
        description="Fast casual - burrito chain, digital ordering",
    ),

    # ========== INDUSTRIAL & INFRASTRUCTURE (7) ==========
    TickerMetadata(
        symbol="CAT",
        name="Caterpillar Inc.",
        category="sector",
        sub_category="industrial",
        weight=0.9,
        description="Construction equipment - infrastructure spending proxy",
    ),
    TickerMetadata(
        symbol="DE",
        name="Deere & Company",
        category="sector",
        sub_category="industrial",
        weight=0.85,
        description="Agriculture equipment - farming machinery, autonomous tractors",
    ),
    TickerMetadata(
        symbol="GE",
        name="General Electric Company",
        category="sector",
        sub_category="industrial",
        weight=0.8,
        description="Aerospace & energy - jet engines, power generation",
    ),
    TickerMetadata(
        symbol="RTX",
        name="RTX Corporation",
        category="sector",
        sub_category="industrial",
        weight=0.85,
        description="Aerospace & defense - Pratt & Whitney, Raytheon",
    ),
    TickerMetadata(
        symbol="LMT",
        name="Lockheed Martin Corporation",
        category="sector",
        sub_category="industrial",
        weight=0.85,
        description="Defense - F-35 fighter jets, missiles",
    ),
    TickerMetadata(
        symbol="FDX",
        name="FedEx Corporation",
        category="sector",
        sub_category="industrial",
        weight=0.8,
        description="Logistics - package delivery, e-commerce enabler",
    ),
    TickerMetadata(
        symbol="URI",
        name="United Rentals Inc.",
        category="sector",
        sub_category="industrial",
        weight=0.75,
        description="Equipment rental - construction equipment rentals",
    ),

    # ========== REAL ESTATE & REITs (4) ==========
    TickerMetadata(
        symbol="PLD",
        name="Prologis Inc.",
        category="sector",
        sub_category="real_estate",
        weight=0.85,
        description="Logistics real estate - warehouses for e-commerce",
    ),
    TickerMetadata(
        symbol="AMT",
        name="American Tower Corporation",
        category="sector",
        sub_category="real_estate",
        weight=0.85,
        description="Cell towers - wireless infrastructure REIT",
    ),
    TickerMetadata(
        symbol="EQIX",
        name="Equinix Inc.",
        category="sector",
        sub_category="real_estate",
        weight=0.85,
        description="Data centers - colocation, cloud infrastructure",
    ),
    TickerMetadata(
        symbol="PSA",
        name="Public Storage",
        category="sector",
        sub_category="real_estate",
        weight=0.75,
        description="Self-storage - storage unit REIT",
    ),

    # ========== INTERNATIONAL GROWTH (5) ==========
    TickerMetadata(
        symbol="JD",
        name="JD.com Inc.",
        category="sector",
        sub_category="consumer",
        weight=0.75,
        description="Chinese e-commerce - direct sales, logistics",
    ),
    TickerMetadata(
        symbol="PDD",
        name="PDD Holdings Inc.",
        category="sector",
        sub_category="consumer",
        weight=0.75,
        description="Chinese e-commerce - Pinduoduo, Temu discount platform",
    ),
    TickerMetadata(
        symbol="BIDU",
        name="Baidu Inc.",
        category="sector",
        sub_category="technology",
        weight=0.75,
        description="Chinese search - Google of China, AI research",
    ),
    TickerMetadata(
        symbol="TSM",
        name="Taiwan Semiconductor Manufacturing",
        category="sector",
        sub_category="technology",
        weight=0.95,
        description="Chip manufacturing - produces NVIDIA, Apple, AMD chips",
    ),
    TickerMetadata(
        symbol="SAP",
        name="SAP SE",
        category="sector",
        sub_category="technology",
        weight=0.8,
        description="European enterprise software - ERP systems",
    ),

    # ========== GAMING & ENTERTAINMENT (5) ==========
    TickerMetadata(
        symbol="RBLX",
        name="Roblox Corporation",
        category="sector",
        sub_category="technology",
        weight=0.75,
        description="Gaming platform - user-generated games, metaverse",
    ),
    TickerMetadata(
        symbol="U",
        name="Unity Software Inc.",
        category="sector",
        sub_category="technology",
        weight=0.7,
        description="Game engine - Unity development platform",
    ),
    TickerMetadata(
        symbol="EA",
        name="Electronic Arts Inc.",
        category="sector",
        sub_category="technology",
        weight=0.8,
        description="Gaming - FIFA, Madden, Battlefield franchises",
    ),
    TickerMetadata(
        symbol="TTWO",
        name="Take-Two Interactive Software",
        category="sector",
        sub_category="technology",
        weight=0.8,
        description="Gaming - Grand Theft Auto, NBA 2K",
    ),
    TickerMetadata(
        symbol="NFLX",
        name="Netflix Inc.",
        category="sector",
        sub_category="technology",
        weight=0.85,
        description="Streaming - video streaming leader, original content",
    ),

    # ========== CYBERSECURITY & SOFTWARE (5) ==========
    TickerMetadata(
        symbol="CRWD",
        name="CrowdStrike Holdings Inc.",
        category="sector",
        sub_category="technology",
        weight=0.9,
        description="Cybersecurity - endpoint security, cloud-native",
    ),
    TickerMetadata(
        symbol="PANW",
        name="Palo Alto Networks Inc.",
        category="sector",
        sub_category="technology",
        weight=0.9,
        description="Cybersecurity - firewalls, cloud security",
    ),
    TickerMetadata(
        symbol="ZS",
        name="Zscaler Inc.",
        category="sector",
        sub_category="technology",
        weight=0.85,
        description="Cloud security - zero trust network access",
    ),
    TickerMetadata(
        symbol="DDOG",
        name="Datadog Inc.",
        category="sector",
        sub_category="technology",
        weight=0.8,
        description="Cloud monitoring - infrastructure monitoring, APM",
    ),
    TickerMetadata(
        symbol="MDB",
        name="MongoDB Inc.",
        category="sector",
        sub_category="technology",
        weight=0.8,
        description="Database - NoSQL database, cloud database services",
    ),
]

print(f"Total stocks to add: {len(ADDITIONS)}")
print("\nCopy the ADDITIONS list above and add to TIER_2_STOCKS in src/config/tickers.py")
