# AAPL - Large Cap Tech, Moderate Volatility
# Characteristics: Steady growth, product cycles, dividend stock

# Risk Management
stop_loss_pct: 0.12          # 12% stop (moderate)
take_profit_pct: 0.25        # 25% target (steady mover)
trailing_stop_enabled: true
trailing_stop_activation: 0.15
trailing_stop_distance: 0.08

# ML Configuration
min_ml_confidence: 0.78      # Higher confidence (less volatile)
use_momentum_filter: true
min_price_strength: 0.02     # 2% above MA
min_volume_ratio: 1.2        # 1.2x volume

# Position Sizing
max_position_size: 0.20      # 20% max
min_position_size: 0.10

# Market Conditions
max_vix_for_entry: 25        # Prefer lower volatility
preferred_regimes:
  - BULLISH

# Technical Indicators
indicators:
  - RSI_14
  - MACD_12_26_9
  - ATR_14
  - BB_PCT_20
  - VOLUME_RATIO_20
  - PRICE_VS_MA_50
  - PRICE_VS_MA_200
  - SECTOR_STRENGTH
